# Generated by Django 3.2.19 on 2023-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0007_remove_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='remove_curve',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
