# Generated by Django 3.2.19 on 2023-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0008_remove_curve_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeStarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_type', models.CharField(max_length=30)),
                ('mainclass', models.CharField(max_length=30)),
                ('type_info', models.CharField(max_length=3000)),
                ('is_subtype', models.BooleanField(default=False)),
            ],
        ),
    ]
