# Generated by Django 3.2.19 on 2023-07-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0009_typestarinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typestarinfo',
            name='is_subtype',
        ),
    ]
